### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Smilebags** [chiunhau/p5-manager#21]
When running p5 serve I get an error saying it cannot open the file .p5rc
This is with an untouched project generated by p5 manager. Not sure what I'm meant to do?

Windows 10
Here's the full error info:

GET /api/p5rc 500 11.255 ms - 1237
Error: ENOENT: no such file or directory, open 'C:\Users\chris\Documents\Web Study\p5\p5-bezier\\.p5rc'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at C:\Users\chris\AppData\Roaming\npm\node_modules\p5-manager\server\server.js:28:27
    at Layer.handle [as handle_request] (C:\Users\chris\AppData\Roaming\npm\node_modules\p5-manager\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\chris\AppData\Roaming\npm\node_modules\p5-manager\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\chris\AppData\Roaming\npm\node_modules\p5-manager\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\chris\AppData\Roaming\npm\node_modules\p5-manager\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\chris\AppData\Roaming\npm\node_modules\p5-manager\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\Users\chris\AppData\Roaming\npm\node_modules\p5-manager\node_modules\express\lib\router\index.js:330:12)

**Comment by chiunhau** [comment]
Hi, @Smilebags Sorry I'm not familiar with Windows system. But have you tried rename the \Web Study\ folder to something like \Web_Study\?? I think the space in the directory name caused the issue (?) Please let me know if you fix it 🙇

**Comment by Smilebags** [comment]
Hi @chiunhau , I have tried the same thing in a directory with no spaces in the path and it still doesn't work.

One thought I had: Is the file meant to exist? If I browse there, there is no file called .p5rc - that seems to be what is triggering the error.

**Comment by chiunhau** [comment]
@Smilebags yes normally there should be a .p5rc file in the **collection** directory you just create with `p5 new`. I am gueessing if you run `p5 serve` in the wrong directory? (you should not run `p5 serve` in a **project** directory)

**Comment by Smilebags** [comment]
I see, I misunderstood the package and how it works - I had the idea that a project could be independent of a collection. I'll follow the instructions next time! Sorry about that.

**Comment by chiunhau** [comment]
@Smilebags `p5 server` is only for collection. But you can also  use `p5 generate --bundle PROJECT_NAME` to create a bundled p5js project anywhere.
