### ISSUE TITLE
p5 generate not finding .p5rc after last update

### ISSUE THREAD

**Issue by andreanidouglas** [chiunhau/p5-manager#29]
__System:__ Debian 9

__Node Version:__ V8.8.1

__NPM Version:__ V5.4.2

__P5-Manager Version:__ V0.3.2

After issuing `p5 update` for the last time, the command `p5 g test` will return the following message if no previous project was created before:

```bash
p5-manager version 0.3.2
   create : test
fs.js:648
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '.p5rc'
    at Object.fs.openSync (fs.js:648:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at /usr/local/lib/node_modules/p5-manager/generator/generator.js:42:30
    at /usr/local/lib/node_modules/p5-manager/generator/generator.js:113:11
    at FSReqWrap.oncomplete (fs.js:137:15)
```

**Comment by andreanidouglas** [comment]
closed: i'm too dumb to realize i needed the -b flag in the first place
