### ISSUE TITLE
Can't generate p5 basic files.

### ISSUE THREAD

**Issue by random-yang** [chiunhau/p5-manager#40]
This is the console result:

```
p5-manager version 0.4.2
   create : my_project
fs.js:660
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '.p5rc'
    at Object.fs.openSync (fs.js:660:18)
    at Object.fs.readFileSync (fs.js:565:33)
    at /usr/local/lib/node_modules/p5-manager/generator/generator.js:43:30
    at /usr/local/lib/node_modules/p5-manager/generator/generator.js:170:9
    at FSReqWrap.oncomplete (fs.js:153:20)
```

**Comment by chiunhau** [comment]
A project has to be generated under a collection. To generate a collection, use `p5 g my_collection`.
