### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Xendergo** [chiunhau/p5-manager#42]
When I try to create a project, I get this error

fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open 'D:\all items\Crazy mapping video project\.p5rc'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at C:\Users\hrovn\AppData\Roaming\npm\node_modules\p5-manager\generator\generator.js:42:30
    at C:\Users\hrovn\AppData\Roaming\npm\node_modules\p5-manager\generator\generator.js:113:11
    at FSReqWrap.oncomplete (fs.js:149:15)

**Comment by chiunhau** [comment]
A project has to be generated under a collection. To generate a collection, use `p5 g my_collection`.
