### ISSUE TITLE
Error: SSL Error: CERT_UNTRUSTED

### ISSUE THREAD

**Issue by drewLough** [chiunhau/p5-manager#43]
Experiencing difficulty installing this package from npm.

```
λ ~/ npm i p5-manager
npm WARN package.json jsesc@1.3.0 No README.md file found!
npm WARN package.json copy-descriptor@0.1.1 No README.md file found!
npm WARN package.json object-copy@0.1.0 No README.md file found!
npm WARN package.json static-extend@0.1.2 No README.md file found!
npm WARN package.json get-value@2.0.6 No README.md file found!
npm http GET https://registry.npmjs.org/p5-manager
npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (/home/dlo/.nvm/v0.8.16/lib/node_modules/npm/node_modules/request/main.js:525:26)
npm ERR!     at ClientRequest.g (events.js:192:14)
npm ERR!     at ClientRequest.EventEmitter.emit (events.js:96:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1462:7)
npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
npm ERR!     at CleartextStream.socketOnData [as ondata] (http.js:1367:20)
npm ERR!     at CleartextStream.CryptoStream._push (tls.js:526:27)
npm ERR!     at SecurePair.cycle (tls.js:880:20)
npm ERR!     at EncryptedStream.CryptoStream.write (tls.js:267:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.17.19-200.fc28.x86_64
npm ERR! command "/home/dlo/.nvm/v0.8.16/bin/node" "/home/dlo/.nvm/v0.8.16/bin/npm" "i" "p5-manager"
npm ERR! cwd /home/dlo
npm ERR! node -v v0.8.16
npm ERR! npm -v 1.1.69
npm ERR! code ESSL
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/dlo/npm-debug.log
npm ERR! not ok code 0

```

**Comment by drewLough** [comment]
Looks like it was caused by an old node version (8 instead of 10). closing.
